test:
  clients:
    default:
      database: govuk_content_shared_test
      hosts:
        - localhost
  options:
    use_activesupport_time_zone: true
    log_level: :error
    belongs_to_required_by_default: false
